services:
  mtprotoproxy:
    build: .
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
        - ./config.py:/home/tgproxy/config.py
        - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
        - /etc/localtime:/etc/localtime:ro
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
#    mem_limit: 768m
