#!/usr/bin/env bash
# =============================================================================
# setup-telemt-node.sh — reproducible MTProto proxy node using telemt
# (Rust/Tokio, https://github.com/telemt/telemt), fake-TLS with real
# front-cert emulation (tls_emulation).
#
# This is what actually runs in production (tldw-server) as of 2026-08,
# replacing the mtg-based setup-mtg-node.sh there. Kept both in this repo:
# telemt is the current default, mtg is a documented alternative (see README).
#
# Usage:
#   sudo DOMAIN=vkvideo.ru PORT=443 USERNAME=proxy bash setup-telemt-node.sh
#
# Idempotent: safe to re-run. Re-running keeps the existing user secret unless
# you pass NEW_SECRET=1.
# =============================================================================
set -euo pipefail

# ---- config (override via env) ----------------------------------------------
DOMAIN="${DOMAIN:-vkvideo.ru}"        # fronting SNI — must serve real TLS 1.3 to
                                       # normal clients (same rule as mtg, see
                                       # the domain-selection checklist in README)
PORT="${PORT:-443}"
USERNAME="${USERNAME:-proxy}"         # access.users key; multiple users = re-run
                                       # with a different USERNAME, or edit config.toml
# Pin deliberately; bump after checking https://github.com/telemt/telemt/releases
TELEMT_VERSION="${TELEMT_VERSION:-3.5.5}"
NEW_SECRET="${NEW_SECRET:-0}"
STATE=/var/lib/telemt
BIN=/usr/local/bin/telemt

log(){ printf '\n\033[1;36m### %s\033[0m\n' "$*"; }
[ "$(id -u)" = 0 ] || { echo "run as root"; exit 1; }
mkdir -p "$STATE" /etc/telemt

# ---- arch detection -----------------------------------------------------------
case "$(uname -m)" in
  x86_64)  ASSET="telemt-x86_64-linux-gnu.tar.gz" ;;
  aarch64) ASSET="telemt-aarch64-linux-gnu.tar.gz" ;;
  *) echo "unsupported arch: $(uname -m)"; exit 1 ;;
esac

# ---- download + verify ---------------------------------------------------------
log "telemt binary ($TELEMT_VERSION, $ASSET)"
BASE_URL="https://github.com/telemt/telemt/releases/download/$TELEMT_VERSION"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
curl -fsSL "$BASE_URL/$ASSET" -o "$TMP/$ASSET"
curl -fsSL "$BASE_URL/$ASSET.sha256" -o "$TMP/$ASSET.sha256"
(cd "$TMP" && sha256sum -c "$ASSET.sha256")
tar -xzf "$TMP/$ASSET" -C "$TMP"
install -m 755 "$TMP/telemt" "$BIN"
"$BIN" --version

# ---- config ---------------------------------------------------------------------
log "config (domain: $DOMAIN, port: $PORT, user: $USERNAME)"
if [ -f "$STATE/secret" ] && [ "$NEW_SECRET" = 0 ]; then
  SECRET="$(cat "$STATE/secret")"
else
  SECRET="$(openssl rand -hex 16)"
  echo "$SECRET" > "$STATE/secret"; chmod 600 "$STATE/secret"
fi
mkdir -p "$STATE/tlsfront"
cat > /etc/telemt/config.toml <<EOF
### telemt — generated by setup-telemt-node.sh, $(date -u +%F)
[general]
use_middle_proxy = false
log_level = "normal"

[general.modes]
classic = false
secure  = false
tls     = true

[general.links]
show = "*"

[server]
port = $PORT

[server.api]
enabled = true
listen = "127.0.0.1:9091"
whitelist = ["127.0.0.1/32", "::1/128"]

[[server.listeners]]
ip = "0.0.0.0"

[censorship]
tls_domain = "$DOMAIN"
mask = true
tls_emulation = true
tls_front_dir = "$STATE/tlsfront"

[access.users]
$USERNAME = "$SECRET"
EOF

# ---- systemd ----------------------------------------------------------------
log "systemd unit"
cat > /etc/systemd/system/telemt.service <<'EOF'
[Unit]
Description=telemt - MTProto proxy for Telegram
Documentation=https://github.com/telemt/telemt
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=/var/lib/telemt
ExecStart=/usr/local/bin/telemt /etc/telemt/config.toml
Restart=always
RestartSec=5
LimitNOFILE=65536

# Only needs to bind on a privileged port (443) — no other root capability.
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/var/lib/telemt

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now telemt
sleep 2
systemctl --no-pager --full status telemt | head -6

# ---- firewall -----------------------------------------------------------------
if command -v ufw >/dev/null; then
  log "ufw"
  ufw allow "$PORT/tcp" >/dev/null || true
fi

# ---- summary ------------------------------------------------------------------
IP="$(curl -s --max-time 8 https://api.ipify.org || echo YOUR_IP)"
log "DONE"
echo "Proxy link (share this):"
echo "  https://t.me/proxy?server=$IP&port=$PORT&secret=$SECRET"
echo
echo "Notes:"
echo "  * Fronting domain $DOMAIN must serve real TLS 1.3 (client masquerade) —"
echo "    see the domain-selection checklist in README.md."
echo "  * Secret stored at $STATE/secret. Re-run with NEW_SECRET=1 to rotate."
echo "  * journald handles log rotation for this service by default; no extra"
echo "    config needed (unlike Docker json-file logs, which have no default cap)."
echo "  * Add more users: re-run with a different USERNAME=..., or edit"
echo "    /etc/telemt/config.toml's [access.users] table directly, then"
echo "    'systemctl restart telemt'."
